# -*- coding: utf-8 -*-
"""mpesa_till.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NOe9wbr_4hsadCKPqK_JunVuSCJqx-fH
"""

import streamlit as st
import pandas as pd
from io import StringIO

def generate_iif(df, bank_account="MPESA Till"):
    # Parse date
    df['Completion Time'] = pd.to_datetime(df['Completion Time'], errors='coerce')
    df['Date'] = df['Completion Time'].dt.strftime('%m/%d/%Y')

    # Exclude DTB settlement transactions
    df = df[~df['Details'].str.contains("Merchant Account to Organization Settlement Account", case=False, na=False)]
    df = df[~df['Other Party Info'].fillna('').str.contains("6126173 - GARIDON", case=False)]

    # Start IIF structure
    iif_lines = [
        "!TRNS\tTRNSTYPE\tDATE\tACCNT\tNAME\tAMOUNT\tDOCNUM\tMEMO",
        "!SPL\tTRNSTYPE\tDATE\tACCNT\tNAME\tAMOUNT\tDOCNUM\tMEMO",
        "ENDTRNS"
    ]

    # Handle payments (Paid In)
    payments = df[df['Paid In'].notna() & (df['Paid In'] > 0)]
    for _, row in payments.iterrows():
        date = row['Date']
        docnum = row['Receipt No.']
        amount = row['Paid In']
        memo = row['Details']
        name = row.get('Other Party Info', 'Customer')

        iif_lines.append(f"TRNS\tDEPOSIT\t{date}\t{bank_account}\t{name}\t{amount:.2f}\t{docnum}\t{memo}")
        iif_lines.append(f"SPL\tDEPOSIT\t{date}\tAccounts Receivable\t{name}\t{-amount:.2f}\t{docnum}\t{memo}")
        iif_lines.append("ENDTRNS")

    # Combine transaction charges
    fees = df[df['Details'].str.contains("Charge", case=False, na=False)]
    if not fees.empty:
        total_fees_by_day = fees.groupby('Date')['Withdrawn'].sum()
        for date, total_fee in total_fees_by_day.items():
            docnum = f"FEE-{date.replace('/', '')}"
            memo = "MPESA Transaction Charges"

            iif_lines.append(f"TRNS\tCHECK\t{date}\t{bank_account}\tMPESA Charges\t{-total_fee:.2f}\t{docnum}\t{memo}")
            iif_lines.append(f"SPL\tCHECK\t{date}\tBank Charges\tMPESA Charges\t{total_fee:.2f}\t{docnum}\t{memo}")
            iif_lines.append("ENDTRNS")

    return "\n".join(iif_lines)

# Streamlit UI
st.set_page_config(page_title="MPESA to QuickBooks IIF", layout="centered")
st.title("MPESA Till ➝ QuickBooks IIF Converter")

uploaded_file = st.file_uploader("Upload MPESA Statement (.csv only)", type=["csv"])

if uploaded_file:
    df = pd.read_csv(uploaded_file)

    st.subheader("Preview")
    st.dataframe(df.head())

    if st.button("Convert to IIF"):
        iif_text = generate_iif(df)

        st.download_button(
            label="Download IIF File",
            data=iif_text,
            file_name="mpesa_till.qb.iif",
            mime="text/plain"
        )